auto-login
What-Should-I-Eat/WSIE pull request #224
Opened 2024-11-19 01:33 UTC by zuhaaaaaaa

Could you review this code. Please let me know any correction it is need

2024-11-19 22:55 UTC, CamronOlsen requested changes
There are some things that will need to be fixed, we can have a discussion to go over things as well.

2024-11-19 22:55 UTC, CamronOlsen commented on client/public/static/js/verification.js
> -      method: PUT_ACTION,
You can leave this as PUT_ACTION, PUT_ACTION is defined as PUT in the constants.js file.

2024-11-19 22:55 UTC, CamronOlsen commented on client/public/static/js/verification.js
> +    method: "PUT",
Please use PUT_ACTION instead of "PUT" if you don't mind to keep consistent across the program.

2024-11-19 22:55 UTC, CamronOlsen commented on client/public/static/js/verification.js
> +      window.location.href = "/dashboard";
Not sure where you got this from, there is no "/dashboard". You can just redirect to home "/".

2024-11-19 22:55 UTC, CamronOlsen commented on client/dist/app.dev.js
> +    // Mock verification logic (replace with actual logic)
Not sure if these comments need to be updated?

2024-11-19 22:55 UTC, CamronOlsen commented on client/dist/app.dev.js
> +    // Generate a mock authentication token (replace with secure token logic like JWT)
If we are using tokens, I am assuming you will need to utilize JWT.

2024-11-22 00:08 UTC, CamronO commented
![image](https://github.com/user-attachments/assets/8c91e6a0-357e-4236-b0bb-4e6d0dd38f78)
You are on the right track I think, your api call seems to be working. Only thing I noticed is it doesn't actually sign the user in after signing up.

2024-12-07 19:48 UTC, closed without merging